### ISSUE TITLE
ConoHa CentOS 7.1 运行出错

### ISSUE THREAD

**Issue by mikelei8291** [mikelei8291/shadowsocks-rss-onekey#10]
`/etc/issue` 内容里没有 "CentOS" 导致无法检测发行版

**Comment by zhangyubaka** [comment]
尝试/proc/version

**Comment by mikelei8291** [comment]
好的，我去试试

**Comment by mikelei8291** [comment]
`Linux version 2.6.32-573.7.1.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Tue Sep 22 22:00:00 UTC 2015`

并没有明显的表示

**Comment by mikelei8291** [comment]
突然 `/etc/issue` 里又有了。。。
不过 `/etc/*-release` 这些里面倒是有

**Comment by mikelei8291** [comment]
Fixed in commit a833630
